[database]
url = "mysql://root:73411bf9-a4a9-4a8a-9716-8935d3@127.0.0.1:3306/group"
[server.grpc]
host = "127.0.0.1"
port = 8003
[server.http]
host = "127.0.0.1"
port = 8203
[sys]
log_leve = "warn"  #trace debug info error warn

[hot_group]
hot_bytes_per_member = 128
hot_bytes_per_group = 64
hot_avg_members = 32
hot_mem_util = 0.5
hot_cap_max = 1000000
hot_cap_min = 1000
hot_tti_secs = 300
shard_count = 1024
per_group_shard = 1
page_cache_cap = 100000
page_cache_tti_secs = 300
persist_debounce_ms = 200
profile_l1_cap = 1000000
profile_l1_tti_secs = 600

# #------------friend_service
# [[friend_service]]
# index = 0
# grpc_addr = "127.0.0.1:8002"

# #------------user_service
# [[user_service]]
# index = 0
# grpc_addr = "127.0.0.1:6001"

# #------------message_service
# [[msg_friend]]
# index = 0
# grpc_addr = "127.0.0.1:8002"

# #------------group_service
# [[msg_group]]
# index = 0
# grpc_addr = "127.0.0.1:8103"
