[database]
url = "mysql://root:73411bf9-a4a9-4a8a-9716-8935d3@127.0.0.1:3306/msg_friend"
[server.grpc]
host = "127.0.0.1"
port = 8102
[server.http]
host = "127.0.0.1"
port = 8302
[sys]
log_leve = "warn"  # trace debug info error warn

[kafka]
broker = "127.0.0.1:9092"
group_id = "msg_friend_dispatcher"
replicas = 1
kafka_user_name=""
kafka_password=""

#------------friend_service
[friend_service]
index = 0
grpc_addr = "127.0.0.1:8002"

#------------msg_system nodes (for system notifications)
[[msg_system_nodes]]
index = 0
grpc_addr = "127.0.0.1:8110"

# #------------app_group_dispatcher
# [[group_service]]
# index = 0
# grpc_addr = "127.0.0.1:8003"

# #------------user_service
# [[user_service]]
# index = 0
# grpc_addr = "127.0.0.1:6001"

#------------group_service
# [[kafka_cfg]]
# index = 0
# kafka_broker = "127.0.0.1:9092"
# kafka_group_id = "msg_group_dispatcher"
# kafka_user_name=""
# kafka_password=""
